# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Thomas Cox
tagline:             'Portfolio'
description:         'This is my portfolio describing my work for the semester tracker project'
url:                 http://lanyon.getpoole.com
baseurl:             '/Coxts2-Portfolio'
paginate:            5

# About/contact
author:
  name:              Thomas Cox
  email:             thomascox86@gmail.com

# Custom vars
version:             1.0.0
